# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Random Amazon Product Generator
email: imfeelingprimey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experience Amazon Prime like never before & get introduced to new products randomly. Are you feeling Primey? A new shopping experience is waiting for you.
twitter:
  username: 
  social:
  name: S
  links:
    - 

github_username:  12oss

# Build settings
markdown:         kramdown
theme:            minima



#Teaser Image
image: /assets/css/images/flat-logo-alt.png


#Logo
logo: /assets/css/images/flat-logo-alt.png

#Pagination
paginate: 10
paginate_path: "/blog/page:num/"


#html compress
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Server
source:           _gh_pages
destination:      docs
#host:             0.0.0.0
port:             12022
baseurl:          ""
#Production : https://12oss.github.io/imfeelingprimey/
#DEV : http://0.0.0.0:12055/imfeelingprimey/
#site.github.url
#site.baseurl
url:              "https://master.d2qvri55t6evsp.amplifyapp.com/"
encoding:         UTF-8


#Compress HTML
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []


# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
 # - github-pages
 # - jekyll-github-metadata

